### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shum-inc** [sebhoerl/Twig-netbeans#1]
{% extends 'AcmeDemoBundle::layout.html.twig' %}

{% block title %}Symfony - Welcome{% endblock %}

{% block content %}

<h1>Welcome!</h1>

```
<p>Congratulations! You have successfully installed a new Symfony application.</p>

<div class="symfony-blocks-welcome">
    <div class="block-quick-tour">
        <div class="illustration">
            <img src="{{ asset('bundles/acmedemo/images/welcome-quick-tour.gif') }}" alt="Quick tour" />
        </div>
        <a class="symfony-button-green" href="http://symfony.com/doc/2.0/quick_tour/index.html">Read the Quick Tour</a>
    </div>
    <div class="block-configure">
        <div class="illustration">
            <img src="{{ asset('bundles/acmedemo/images/welcome-configure.gif') }}" alt="Configure your appication" />
        </div>
        <a class="symfony-button-green" href="{{ path('_configurator_home') }}">Configure</a>
    </div>
    <div class="block-demo">
        <div class="illustration">
            <img src="{{ asset('bundles/acmedemo/images/welcome-demo.gif') }}" alt="Demo" />
        </div>
        <a class="symfony-button-green" href="{{ path('_demo') }}">Run The Demo</a>
    </div>
</div>

<div class="symfony-blocks-help">
    <div class="block-documentation">
        <ul>
            <li><strong>Documentation</strong></li>
            <li><a href="http://symfony.com/doc/2.0/book/index.html">The book</a></li>
            <li><a href="http://symfony.com/doc/2.0/reference/index.html">The cookbook</a></li>
            <li><a href="http://symfony.com/doc/2.0/glossary/index.html">Glossary</a></li>
        </ul>
    </div>
    <div class="block-documentation-more">
        <ul>
            <li>&nbsp;</li>
            <li><a href="http://symfony.com/doc/2.0/contributing/index.html">Contributing</a></li>
            <li><a href="http://trainings.sensiolabs.com">Trainings</a></li>
            <li><a href="http://books.sensiolabs.com">Books</a></li>
        </ul>
    </div>
    <div class="block-community">
        <ul>
            <li><strong>Community</strong></li>
            <li><a href="http://symfony.com/irc">IRC channel</a>
            <li><a href="http://symfony.com/mailing-lists">Mailing lists</a></li>
            <li><a href="http://forum.symfony-project.org">Forum</a></li>
            <li><a href="http://symfony.com/doc/2.0/contributing/index.html">How to be involved</a></li>
            <li><a href="http://symfony.com/doc/2.0/contributing/index.html">Contributing</a></li>
        </ul>
    </div>
</div>
```

{% endblock %}

**Comment by shum-inc** [comment]
java.lang.AssertionError: Token length=0 <= 0
    at org.netbeans.lib.lexer.token.DefaultToken.<init>(DefaultToken.java:87)
    at org.netbeans.lib.lexer.LexerInputOperation.createDefaultTokenInstance(LexerInputOperation.java:306)
    at org.netbeans.lib.lexer.LexerInputOperation.createToken(LexerInputOperation.java:284)
    at org.netbeans.spi.lexer.TokenFactory.createToken(TokenFactory.java:105)
    at org.netbeans.spi.lexer.TokenFactory.createToken(TokenFactory.java:89)
    at org.netbeans.php.twig.lexer.NbTwigLexer.nextToken(NbTwigLexer.java:57)
    at org.netbeans.lib.lexer.LexerInputOperation.nextToken(LexerInputOperation.java:193)
    at org.netbeans.lib.lexer.BatchTokenList.tokenOrEmbeddingImpl(BatchTokenList.java:178)
    at org.netbeans.lib.lexer.BatchTokenList.tokenOrEmbedding(BatchTokenList.java:173)
    at org.netbeans.api.lexer.TokenSequence.moveIndex(TokenSequence.java:560)
    at org.netbeans.api.lexer.TokenSequence.moveStart(TokenSequence.java:578)
    at org.netbeans.php.twig.TwigEmbeddingProvider.getEmbeddings(TwigEmbeddingProvider.java:26)
    at org.netbeans.modules.parsing.impl.SourceCache.refresh(SourceCache.java:319)
[catch] at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:661)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by sebhoerl** [comment]
Code may now start with a markup. Closed by ebd749030936dcd3e69500e3e5d4b6a7af2abdcf.

**Comment by shum-inc** [comment]
Can You share compiled version with this fix ?

**Comment by sebhoerl** [comment]
just uploaded it
